extraction:
  cpp:
    prepare:
      packages: "cmake"
    configure:
      command:
      - "pip3 install --upgrade --user meson"
      - "meson build"
    index:
      build_command: "ninja -j4 -C build"